config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get 'pages/home', to: 'pages#home'

  resources :recipes do
    resources :comments, only: [:create]
  end

  get '/signup' , to: 'chefs#new'
  resources :chefs, except: [:new]

  get '/login' , to: 'sessions#new'
  post '/login' , to: 'sessions#create'
  get '/logout' , to: 'sessions#destroy'

  resources :ingredients , except: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chef.rb
class Chef < ApplicationRecord
	
	before_save {self.email = email.downcase  }
	validates :name, presence: true, length: { maximum: 30 }
  	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  	validates :email, presence: true, length: { maximum: 255 },
        format: { with: VALID_EMAIL_REGEX },
        uniqueness: { case_sensitive: false }

    
    has_many :recipes , dependent: :destroy
    has_secure_password
    validates :password, presence: true, length: {minimum: 5}, allow_nil: true
    has_many :comments, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
	validates :description, presence: true, length: {minimum: 4, maximum: 150}
	belongs_to :chef
	belongs_to :recipe
	validates :chef_id, presence: true
	validates :recipe_id, presence: true
	default_scope -> { order(updated_at: :desc)}
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
	validates :name, presence: true, length: {minimum: 3, maximum: 30}
	validates_uniqueness_of :name

	has_many :recipe_ingredients
	has_many :recipes, through: :recipe_ingredients
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	validates :name, presence: true
	validates :description, presence: true , length: {minimum: 5, maximum: 500}
	validates :chef_id, presence: true

	belongs_to :chef
	default_scope -> { order(updated_at: :desc)}

	has_many :recipe_ingredients
	has_many :ingredients , through: :recipe_ingredients
	has_many :comments, dependent: :destroy
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
	belongs_to :recipe
	belongs_to :ingredient 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

	helper_method :current_chef, :logged_in?

	def current_chef
		@current_chef ||= Chef.find(session[:chef_id]) if session[:chef_id]
	end

	def logged_in?
		!!current_chef
	end

	def require_user
		if !logged_in?
			flash[:danger] = "You must be logged in"
			redirect_to root_path
		end
	end
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController

	before_action :set_chef, only: [:show, :edit, :update, :destroy]
	before_action :require_same_user, only: [:edit, :update, :destroy]
	before_action :require_admin, only: [:destroy]

	def index
		@chefs = Chef.paginate(page: params[:page], per_page: 5)
	end

	def new
		@chef = Chef.new
	end

	def create
		@chef = Chef.new(chef_params)

		if @chef.save
			session[:chef_id] = @chef.id
			flash[:success] = "Welcome #{@chef.name} to Recipe app!"
			redirect_to chef_path(@chef)
		else
			render 'new'
		end
	end

	def show
		@chef_recipes= @chef.recipes.paginate(page: params[:page], per_page: 5)
	end

	def edit
	end

	def update
		if @chef.update(chef_params)
			flash[:success] = "Your account updated successfully"
			redirect_to @chef
		else
			render 'edit'
		end
	end

	def destroy
		if !@chef.admin?
			@chef.destroy
			flash[:danger]="Chef and all associated recipes deleted successfully!"
			redirect_to chefs_path
		end
	end

	private

	def require_same_user
		if current_chef != @chef and !current_chef.admin?
			flash[:danger] = "You do not have permission to do this!"
			redirect_to chefs_path
		end
	end

	def require_admin
		if logged_in? && !current_chef.admin?
			flash[:danger] = "Only admin can perform this action"
			redirect_to root_path
		end
	end



	def set_chef
		@chef= Chef.find(params[:id])
	end
	
	def chef_params
		params.require(:chef).permit(:name ,:email ,:password, :password_confirmation)
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_action :require_user

	def create
		@recipe = Recipe.find(params[:recipe_id])
		@comment = @recipe.comments.build(comment_params)
		@comment.chef = current_chef

		if @comment.save
			flash[:success] = "Commnet was created successfully"
			redirect_to recipe_path(@recipe)
		else
			flash[:danger] = "Commnet was not created"
			redirect_to recipe_path(@recipe)
		end
	end

	private

	def comment_params
		params.require(:comment).permit(:description)
	end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

	before_action :set_ingredient, only: [:edit, :show, :update]
	before_action :require_admin, except: [:show, :index]

	def index
		@ingredients = Ingredient.paginate(page: params[:page], per_page: 5)
	end

	def show
		@ingredient_recipes= @ingredient.recipes.paginate(page: params[:page], per_page: 5)
	end

	def edit

	end

	def new
		@ingredient = Ingredient.new
	end

	def create
		@ingredient = Ingredient.new(ingredient_params)
		if @ingredient.save
			flash[:success]="Ingredient was added successfully"
			redirect_to ingredient_path(@ingredient)
		else
			render 'new'
		end
	end

	def update
		if @ingredient.update(ingredient_params)
			flash[:success]="Ingredient updated successfully"
			redirect_to ingredient_path(@ingredient)
		else
			render 'edit'
		end
	end	

	private

	def set_ingredient
		@ingredient = Ingredient.find(params[:id])
	end

	def ingredient_params
		params.require(:ingredient).permit(:name)
	end

	def require_admin
		if(!logged_in? || (logged_in? and !current_chef.admin?))
			flash[:danger] = "Only admin can perform this action"
			redirect_to ingredients_path
		end
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
		redirect_to recipes_path if logged_in?
	end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

	before_action :set_recipe ,only: [:show, :edit, :update, :destroy]
	before_action :require_user, except: [:index, :show]
	before_action :require_same_user, only: [:edit, :update, :destroy]

	def index
		@recipes = Recipe.paginate(page: params[:page], per_page: 5)
	end

	def show
		@comment = Comment.new
		@comments = @recipe.comments.paginate(page: params[:page],per_page: 5)
	end

	def new
		@recipe = Recipe.new
	end

	def create 
		@recipe = Recipe.new(recipe_params)
		@recipe.chef= current_chef
		if @recipe.save
			flash[:success]="Recipe added successfully"
			redirect_to recipe_path(@recipe)
		else
			render 'new'
		end

	end

	def edit
	end

	def update
		if @recipe.update(recipe_params)
			flash[:success] = "Recipe updated successfully!"
			redirect_to recipe_path(@recipe)
		else
			render 'edit'
		end
	end

	def destroy
		Recipe.find(params[:id]).destroy
		flash[:success] = "Recipe deleted successfully!"
		redirect_to recipes_path
	end

	private
	
	def set_recipe
		@recipe = Recipe.find(params[:id])
	end

	def require_same_user
		if current_chef != @recipe.chef && !current_chef.admin?
			flash[:danger] = "You can not do this"
			redirect_to recipes_path
		end
	end

	def recipe_params
		params.require(:recipe).permit(:name, :description, ingredient_ids: [])
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	
	end
	

	def create
		
		chef= Chef.find_by(email: params[:session][:email].downcase)
		if chef && chef.authenticate(params[:session][:password])
			session[:chef_id] = chef.id
			flash[:success] = "You have successfully logged in"
			redirect_to chef_path(chef)
		else
			flash.now[:danger] = "There's something wrong with entered credentials"
			render 'new'
		end

	end

	def destroy
		session[ :chef_id] = nil
		flash[ :success] = "You have logged out"
		redirect_to root_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def gravatar_for(chef, options = { size: 80})
		gravatar_id = Digest::MD5::hexdigest(chef.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avator/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: chef.name , class: "img-circle")
	end

end

app/views/chefs/_form.html.erb
<%= render 'shared/errors' , obj: @chef%>

<div class="row">
	<div class="col-md-4">
		<%= form_for(@chef, :html => {class: "form-horizontal", role:"form"}) do |new|%>
			<div class="form-group">
				<%= new.label :name%>
				<%= new.text_field :name , class: "form-control" ,placeholder: "Enter your name", autofocus: true %>
			</div>
			<div class="form-group">
				<%= new.label :email%>
				<%= new.email_field :email ,class: "form-control" ,placeholder: "Enter Email", autofocus: true %>
			</div>

			<div class="form-group">
				<%= new.label :password%>
				<%= new.password_field :password ,class: "form-control" ,placeholder: "Choose a password", autofocus: true %>
			</div>


			<div class="form-group">
				<%= new.label :password_confirmation, "Confirm Password"%>
				<%= new.password_field :password_confirmation ,class: "form-control" ,placeholder: "Confirm password", autofocus: true %>
			</div>


			<div class="form-group">
				<%= new.submit(@chef.new_record? ? "Create my account" : "Update my account",class: "btn btn-primary btn-xlarge")%>
			</div>

		<% end %>
		
	</div>
</div>
<hr/>

app/views/chefs/edit.html.erb
<%= render '/shared/page-title', title: 'Edit your Profile'%>

<%= render 'form'%>

app/views/chefs/index.html.erb
<%= render '/shared/page-title', title: 'All Chefs'%>

<div align="center">
<span style="display: block;"><%= will_paginate %></span>
	<% @chefs.each do |chef| %>
		<div class="well col-md-4 col-md-offset-4">
			<ul class="listing">
			
				<li class="title-name"><%= link_to chef.name.capitalize , chef_path(chef) %></li>
				<li><small> <%= pluralize(chef.recipes.count, "recipe") if chef.recipes %> </small></li>
				<% if logged_in? && current_chef.admin? && !chef.admin?%>
					<li><%= link_to "Delete this Chef", chef_path(chef), method: :delete,
						data: {confirm: "Are you sure you want to delete?"} %></li>
				<%end%>
			<ul>
		</div>
	<% end %>
</div>

app/views/chefs/new.html.erb
<%= render '/shared/page-title', title: 'Sign up! New Chef'%>

<%= render 'form'%>

app/views/chefs/show.html.erb
<%= render 'shared/page-title', title: "Welcome to #{@chef.name.capitalize}'s Recipes"%>

<% if @chef.recipes.count !=0 %>
	<div align="center">
		<%= will_paginate @chef_recipes %>
	</div>
	<%= render 'recipes/recipe' , obj: @chef_recipes%>

	<div align="center">
		<%= will_paginate @chef_recipes %>
	</div>
<% else %>
	<h4 align="center">No Recipes yet!</h4>

<% end %>

app/views/comments/_comment.html.erb
<div class="row">
	<div class="col-md-8 well">
		<p><%= comment.description %></p>
		<p>
			<span class="quiet"><small>Created: <%= time_ago_in_words(comment.created_at)%> ago by <%= comment.chef.name%></small></span>
		</p>
	</div>
</div>

app/views/comments/_comments.html.erb
<div align="center">
	<%= will_paginate comments %>
</div>

<% comments.each do |comment| %>
	<%= render(partial: 'comments/comment', object: comment)%>
<% end %>

<div align="center">
	<%= will_paginate comments %>
</div>

app/views/ingredients/_form.html.erb
<%= render 'shared/errors' ,obj: @ingredient%>

<div class="row">
	<div class="col-md-12">
		<%= form_for(@ingredient, :html => {class: "form-horizontal", role:"form"}) do |new|%>
			<div class="form-group">
				<%= new.label :name%>
				<%= new.text_field :name , class: "form-control" ,placeholder: "Enter name of Ingredient", autofocus: true %>

			</div>
			<div class="form-group">
				<%= new.submit(@ingredient.new_record? ? "Create new Ingredient" : "Update Ingredient" ,class: "btn btn-primary btn-xlarge")%>
			</div>

		<% end %>

		<div class="col-md-4 col-md-offset-4 colormatch">
		[<%= link_to "Cancel and go back", recipes_path %>]
		</div>
	</div>
</div>
<hr/>

app/views/ingredients/_ingredient.html.erb
<span class="badge"><%= link_to ingredient.name, ingredient_path(ingredient) %> &nbsp; </span>

app/views/ingredients/edit.html.erb
<%= render '/shared/page-title', title: 'Edit Ingredient Name'%>
<%= render 'form'%>

app/views/ingredients/index.html.erb
<%= render '/shared/page-title', title: 'Available Ingredients'%>

<div align="center">
<span style="display: block;"><%= will_paginate %></span>
	<% @ingredients.each do |ing| %>
		<div class="well col-md-4 col-md-offset-4">
			<ul class="listing">
			
				<li class="title-name"><%= link_to ing.name.capitalize , ingredient_path(ing) %></li>
				<li><small> <%= pluralize(ing.recipes.count, "recipe") if ing.recipes %> </small></li>

				<% if logged_in? && current_chef.admin?%>
					<li><%= link_to "Edit this Ingredient", edit_ingredient_path(ing) %></li>
				<%end%>
			<ul>
		</div>
	<% end %>
</div>

app/views/ingredients/new.html.erb
<%= render '/shared/page-title', title: 'Create a New Ingredient'%>

<%= render 'form'%>

app/views/ingredients/show.html.erb
<%= render 'shared/page-title', title: "#{@ingredient.name.capitalize}"%>

<div>
	<h3>Recipes containing <%= @ingredient.name%></h3>
</div>

<% if @ingredient.recipes.count !=0 %>
	<div align="center">
		<%= will_paginate @ingredient_recipes %>
	</div>
	<%= render 'recipes/recipe' , obj: @ingredient_recipes%>

	<div align="center">
		<%= will_paginate @ingredient_recipes %>
	</div>
<% else %>
	<h4 align="center">No Recipes yet!</h4>

<% end %>

app/views/layouts/_footer.html.erb
  <!-- Site footer -->
    <footer class="site-footer">
      <div class="container">
        <div class="row">
          <div class="col-sm-12 col-md-6">
            <h4>About</h4>
            <p class="text-justify">Scanfcode.com <i>CODE WANTS TO BE SIMPLE </i> is an initiative  to help the upcoming programmers with the code. Scanfcode focuses on providing the most efficient code or snippets as the code wants to be simple. We will help programmers build up concepts in different programming languages that include C, C++, Java, HTML, CSS, Bootstrap, JavaScript, PHP, Android, SQL and Algorithm.</p>
          </div>

          <div class="col-xs-6 col-md-3">
            <h4>Categories</h4>
            <ul class="footer-links">
              <li><a href="http://scanfcode.com/category/c-language/">C</a></li>
              <li><a href="http://scanfcode.com/category/front-end-development/">UI Design</a></li>
              <li><a href="http://scanfcode.com/category/back-end-development/">PHP</a></li>
              <li><a href="http://scanfcode.com/category/java-programming-language/">Java</a></li>
              <li><a href="http://scanfcode.com/category/android/">Android</a></li>
              <li><a href="http://scanfcode.com/category/templates/">Templates</a></li>
            </ul>
          </div>

          <div class="col-xs-6 col-md-3">
            <h4>Quick Links</h4>
            <ul class="footer-links">
              <li><a href="http://scanfcode.com/about/">About Us</a></li>
              <li><a href="http://scanfcode.com/contact/">Contact Us</a></li>
              <li><a href="http://scanfcode.com/contribute-at-scanfcode/">Contribute</a></li>
              <li><a href="http://scanfcode.com/privacy-policy/">Privacy Policy</a></li>
              <li><a href="http://scanfcode.com/sitemap/">Sitemap</a></li>
            </ul>
          </div>
        </div>
        <hr>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-md-8 col-sm-6 col-xs-12">
            <p class="copyright-text">Copyright &copy; 2021 All Rights Reserved by 
              <%= link_to "Recipes.", root_path %>
            </p>
          </div>
        </div>
      </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-1">
		<% flash.each do |name, msg| %>
			<div class="alert alert-<%=name%>">
				<a href="#" class="close" data-dismiss="alert">&#215;</a>
				<%= msg %>
			</div>
		<% end %>
	</div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Recipe', root_path , class: "navbar-brand"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Recipes', recipes_path%></li>
        <li><%= link_to 'Chefs' , chefs_path %></li>
        
        <% if logged_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">More <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Create a new Recipe' , new_recipe_path %></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
        <% end %>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Others <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'All Ingredients' , ingredients_path %></li>
            <li role="separator" class="divider"></li>
            <% Ingredient.all.each do |ing| %>
              <li><%= link_to ing.name.capitalize , ingredient_path(ing) %></li>
            <% end %>
            <% if logged_in? && current_chef.admin? %>
              <li role="separator" class="divider"></li>
              <li><%= link_to "New Ingredient", new_ingredient_path %></li>
            <% end %>
          </ul>
        </li>


      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_chef.name.capitalize %>'s Profie <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'View you profile', chef_path(current_chef) %></li>
              <li><%= link_to 'Edit you profile', edit_chef_path(current_chef) %></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to 'Log out', logout_path %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Log in' , login_path %></li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Latest compiled and minified CSS -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/navigation'%>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
  <%= render 'layouts/footer' %>
</html>

app/views/pages/home.html.erb
<div class="jumbotron center">
	<h1>Welcome to my Recipes</h1>
	<h2>The best recipe app.</h2>

	<p><%= link_to "Sign up or Log in","/signup" ,class: "btn btn-danger btn-lg btn-xlarge" %> </p>
	
</div>

<p><%= link_to "Show all Recipes","/recipes/" ,class: "btn btn-success btn-lg btn-xlarge" %> </p>

<div class="container px-4 py-5" id="hanging-icons">
<h3 class="pb-2 border-bottom">Hanging icons</h3>

<div class="row">
  <div class="col-lg-4">
    <div class="icon-square bg-light text-dark flex-shrink-0 me-3">
      <svg class="bi" width="1em" height="1em"><use xlink:href="#toggles2"/></svg>
    </div>
    <div>
      <h2>Featured title</h2>
      <p>Paragraph of text beneath the heading to explain the heading. We'll add onto it with another sentence and probably just keep going until we run out of words.</p>
      <a href="#" class="btn btn-primary btn-xlarge">
        Primary button
      </a>
    </div>
  </div>
  <div class="col-lg-4">
    <div class="icon-square bg-light text-dark flex-shrink-0 me-3">
      <svg class="bi" width="1em" height="1em"><use xlink:href="#cpu-fill"/></svg>
    </div>
    <div>
      <h2>Featured title</h2>
      <p>Paragraph of text beneath the heading to explain the heading. We'll add onto it with another sentence and probably just keep going until we run out of words.</p>
      <a href="#" class="btn btn-primary btn-xlarge">
        Primary button
      </a>
    </div>
  </div>
  <div class="col-lg-4">
    <div class="icon-square bg-light text-dark flex-shrink-0 me-3">
      <svg class="bi" width="1em" height="1em"><use xlink:href="#tools"/></svg>
    </div>
    <div>
      <h2>Featured title</h2>
      <p>Paragraph of text beneath the heading to explain the heading. We'll add onto it with another sentence and probably just keep going until we run out of words.</p>
      <a href="#" class="btn btn-primary btn-xlarge">
        Primary button
      </a>
    </div>
  </div>
</div>
</div>
<br>
<br>
<br>

app/views/recipes/_form.html.erb
<%= render 'shared/errors' , obj: @recipe%>

<div class="row">
	<div class="col-md-12">
		<%= form_for(@recipe, :html => {class: "form-horizontal", role:"form"}) do |new|%>
			<div class="form-group">
				<%= new.label :name%>
				<%= new.text_field :name , class: "form-control" ,placeholder: "Enter name of Recipe", autofocus: true %>
			</div>
			<div class="form-group">
				<%= new.label :description%>
				<%= new.text_area :description ,rows: 10 ,class: "form-control" ,placeholder: "Enter Steps to create Recipe", autofocus: true %>
			</div>

			<div class="form-group">
				<div class="row">
					<div class="col-md-12">
						<%= new.collection_check_boxes :ingredient_ids, Ingredient.all, :id,:name do |cb| %>
							<% cb.label(class: "checkbox-inline input_checkbox") { cb.check_box(class: "check_box") + cb.text} %>
						<% end %>
					</div>
				</div>
			</div>

			<div class="form-group">
				<%= new.submit class: "btn btn-primary btn-xlarge"%>
			</div>

		<% end %>

		<div class="col-md-4 col-md-offset-4 colormatch">
		[<%= link_to "Cancel and go back", recipes_path %>]
		</div>
	</div>
</div>
<hr/>

app/views/recipes/_recipe.html.erb
<% if logged_in? %>
	<div class="pull-right">
		<%= link_to "Add New Recipe", new_recipe_path(@recipe), class: "btn btn-success" %>
	</div>
<% end %>
<% obj.each do |recipe| %>
<div class="row">
	<div class="well  col-md-8">
		<h4><%= link_to recipe.name , recipe_path(recipe) %></h4>
		<p><%= recipe.description %></p>
		<% if recipe.ingredients.any? %>
			<p>Ingredients: <%= render recipe.ingredients%></p>
		<% end %>
		<small>created by <b><%=  recipe.chef.name %></b> <%= time_ago_in_words(recipe.created_at) %> ago | <%= pluralize(recipe.comments.count, "Comment")%></small>
	
		<div class="col-md-6">
			<% if logged_in? && (recipe.chef==current_chef || current_chef.admin? )%>
				<%= link_to "Edit this Recipe", edit_recipe_path(recipe),class:"btn btn-primary"%>
				<%= link_to "Delete this Recipe", recipe_path(recipe), method: :delete, data: {confirm: "Are you sure you want to delete this Recipe"}, class: "btn btn-danger" %>
			<% end %>
		</div>
	</div>
</div>
<% end %>


<hr/>

app/views/recipes/edit.html.erb
<%= render '/shared/page-title', title: 'Edit Exsisting Recipe'%>

<%= render 'form' %>

app/views/recipes/index.html.erb
<%= render 'shared/page-title', title: "List of all Recipes" %>

<div align="center">
	<%= will_paginate @recipes %>
</div>

<%= render 'recipe' , obj: @recipes %>

<div align="center">
	<%= will_paginate @recipes %>
</div>

app/views/recipes/new.html.erb
<%= render '/shared/page-title', title: 'Add new Recipe'%>

<%= render 'form' %>

app/views/recipes/show.html.erb
<%= render 'shared/page-title', title: @recipe.name %>
	
<div class="row">
	<div class="col-md-8">
		<h3> Description </h3>
		<hr/>
		<p style="font-size: 18px"><%= simple_format(@recipe.description.capitalize) %></p>
		<% if @recipe.ingredients.any? %>
			<p>Ingredients: <%= render @recipe.ingredients %></p>
		<% end %>
		<small style="font-size:10px">Created by <%= @recipe.chef.name %></small>
		<div class="pull-right">
			<%= link_to gravatar_for(@recipe.chef), chef_path(@recipe.chef) %>
			<small style="font-size:10px"><%= time_ago_in_words(@recipe.created_at)%>  ago</small>
		</div>
	</div>

</div>
<div class="row">
	<div class="col-md-6">
		<% if logged_in? && (@recipe.chef==current_chef || current_chef.admin? ) %>
			<%= link_to "Edit this Recipe", edit_recipe_path(@recipe),class:"btn btn-warning"%>
			<%= link_to "Delete this Recipe", recipe_path(@recipe), method: :delete, data: {confirm: "Are you sure you want to delete this Recipe"}, class: "btn btn-danger" %>
		<% end %>
		<%= link_to "Go Back", recipes_path,class:"btn btn-primary"%>
	</div>
</div>
<hr/>
<% if logged_in? %>
	<div class="row">
		<div class="col-md-6">
			<%= form_for([@recipe,@comment], :html => {class: "form-horizontal", role:"form"}) do |new|%>
				<div class="form-group">
					<%= new.label :description, "Post a Comment" %>
					<%= new.text_area :description ,rows: 4 ,class: "form-control" ,placeholder: "Enter comment here", autofocus: true %>
				</div>
				<div class="form-group">
					<%= new.submit "Comment" ,class: "btn btn-primary btn-xlarge"%>
				</div>
			<% end %>
		</div>
	</div>
<% end %>
</hr>
<%if @recipe.comments.count != 0 %>
	<div class="row">
		<div class="col-md-8">
			<h3>Comments: </h3>
			<%= render partial: 'comments/comments', object: @comments %>
		</div>
	</div>
<%else%>
	<div class="row">
		<div class="col-md-8">
			<h3> No Comments yet! </h3>
		</div>
	</div>
<%end%>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any?%>
	<div class="panel panel-danger">
		<div class="panel-heading">
			<div class="panel-title">
				<%= pluralize(obj.errors.count, "error")%>
				prohibited saved <%= obj.class %> from 
			</div>
			<div class="panel-body">
				<%= obj.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</div>
		</div>
	</div>
<% end %>

app/views/shared/_page-title.html.erb
<h1> <%=title%> </h1>
<hr />